<?php

namespace Container3uzaS2i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscribeControllerunsubscribeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vFMvPs.App\Controller\Api\SubscribeController::unsubscribe()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vFMvPs.App\\Controller\\Api\\SubscribeController::unsubscribe()'] = ($container->privates['.service_locator.1vFMvPs'] ?? $container->load('get_ServiceLocator_1vFMvPsService'))->withContext('App\\Controller\\Api\\SubscribeController::unsubscribe()', $container);
    }
}
