<?php

namespace Container3uzaS2i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerupdateRefreshService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OA38qqg.App\Controller\Api\UserController::updateRefresh()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OA38qqg.App\\Controller\\Api\\UserController::updateRefresh()'] = ($container->privates['.service_locator.OA38qqg'] ?? $container->load('get_ServiceLocator_OA38qqgService'))->withContext('App\\Controller\\Api\\UserController::updateRefresh()', $container);
    }
}
