<?php

namespace ContainerHzy8vPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PostService' shared autowired service.
     *
     * @return \App\Service\PostService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PostService.php';

        return $container->privates['App\\Service\\PostService'] = new \App\Service\PostService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
