<?php

namespace ContainerZaQYxsX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Authenticator_AccessToken_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.authenticator.access_token.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AccessTokenAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessToken/AccessTokenHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/AccessTokenHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessToken/AccessTokenExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessToken/HeaderAccessTokenExtractor.php';

        return $container->privates['debug.security.authenticator.access_token.main'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator(new \Symfony\Component\Security\Http\Authenticator\AccessTokenAuthenticator(new \App\Security\AccessTokenHandler(($container->privates['App\\Repository\\AccessTokenRepository'] ?? $container->load('getAccessTokenRepositoryService'))), new \Symfony\Component\Security\Http\AccessToken\HeaderAccessTokenExtractor(), ($container->privates['security.user.provider.concrete.app_user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_AppUserProviderService')), NULL, NULL, NULL));
    }
}
