<?php

namespace Container4m9So3Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__NcsenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..ncsen_' shared service.
     *
     * @return \App\Controller\Api\TokenStorageInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Api\\PostController::delete()": the $tokenStorage argument is type-hinted with the non-existent class or interface: "App\\Controller\\Api\\TokenStorageInterface". Did you forget to add a use statement?');
    }
}
