<?php

namespace Container4m9So3Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllercheckIfBlockedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ZSKOQS.App\Controller\Api\LikeController::checkIfBlocked()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ZSKOQS.App\\Controller\\Api\\LikeController::checkIfBlocked()'] = ($container->privates['.service_locator.8ZSKOQS'] ?? $container->load('get_ServiceLocator_8ZSKOQSService'))->withContext('App\\Controller\\Api\\LikeController::checkIfBlocked()', $container);
    }
}
