<?php

namespace Container4m9So3Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dAnfuH_.App\Controller\Api\PostController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dAnfuH_.App\\Controller\\Api\\PostController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'repostRepo' => ['privates', 'App\\Repository\\RepostRepository', 'getRepostRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'subscribeRepo' => ['privates', 'App\\Repository\\SubscribeRepository', 'getSubscribeRepositoryService', true],
        ], [
            'postRepo' => 'App\\Repository\\PostRepository',
            'repostRepo' => 'App\\Repository\\RepostRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'subscribeRepo' => 'App\\Repository\\SubscribeRepository',
        ]))->withContext('App\\Controller\\Api\\PostController::index()', $container);
    }
}
