<?php

namespace Container4m9So3Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerpatch2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fIPS55..App\Controller\Api\PostController::patch()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fIPS55..App\\Controller\\Api\\PostController::patch()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.fIPS55..App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.fIPS55.": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenStorage' => ['privates', '.errored.c0iUn49', NULL, 'Cannot determine controller argument for "App\\Controller\\Api\\PostController::patch()": the $tokenStorage argument is type-hinted with the non-existent class or interface: "App\\Controller\\Api\\TokenStorageInterface". Did you forget to add a use statement?'],
        ], [
            'post' => 'App\\Entity\\Post',
            'em' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\Api\\PostController::patch()', $container);
    }
}
