<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockedControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9A0dFU3.App\Controller\Api\BlockedController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9A0dFU3.App\\Controller\\Api\\BlockedController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.9A0dFU3.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.9A0dFU3": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'blockedRepo' => ['privates', 'App\\Repository\\BlockedRepository', 'getBlockedRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'blockedRepo' => 'App\\Repository\\BlockedRepository',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\Api\\BlockedController::get()', $container);
    }
}
