<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockedControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D.h5FOk.App\Controller\Api\BlockedController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D.h5FOk.App\\Controller\\Api\\BlockedController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blockedRepo' => ['privates', 'App\\Repository\\BlockedRepository', 'getBlockedRepositoryService', true],
        ], [
            'blockedRepo' => 'App\\Repository\\BlockedRepository',
        ]))->withContext('App\\Controller\\Api\\BlockedController::index()', $container);
    }
}
