<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mV.2Uzz.App\Controller\Api\LikeController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mV.2Uzz.App\\Controller\\Api\\LikeController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'likeRepository' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'likeRepository' => 'App\\Repository\\LikeRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Api\\LikeController::get()', $container);
    }
}
