<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerpatchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NC3526Z.App\Controller\Admin\PostController::patch()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NC3526Z.App\\Controller\\Admin\\PostController::patch()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.NC3526Z.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.NC3526Z": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'post' => 'App\\Entity\\Post',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\PostController::patch()', $container);
    }
}
