<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepostControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8mF5PJs.App\Controller\Api\RepostController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8mF5PJs.App\\Controller\\Api\\RepostController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'repostRepo' => ['privates', 'App\\Repository\\RepostRepository', 'getRepostRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'postRepo' => 'App\\Repository\\PostRepository',
            'repostRepo' => 'App\\Repository\\RepostRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Api\\RepostController::create()', $container);
    }
}
