<?php

namespace ContainerN6uox2s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRespondControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BEK1cPS.App\Controller\Api\RespondController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BEK1cPS.App\\Controller\\Api\\RespondController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'respondRepository' => ['privates', 'App\\Repository\\RespondRepository', 'getRespondRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'respondRepository' => 'App\\Repository\\RespondRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Api\\RespondController::get()', $container);
    }
}
