<?php

namespace ContainerKNzaxCV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscribeControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQhs04o.App\Controller\Api\SubscribeController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bQhs04o.App\\Controller\\Api\\SubscribeController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.bQhs04o.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.bQhs04o": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'subscribeRepo' => ['privates', 'App\\Repository\\SubscribeRepository', 'getSubscribeRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'subscribeRepo' => 'App\\Repository\\SubscribeRepository',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\Api\\SubscribeController::get()', $container);
    }
}
