<?php

namespace ContainerOAgRlbq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2su36sl.App\Controller\PostController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2su36sl.App\\Controller\\PostController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postService' => ['privates', 'App\\Service\\PostService', 'getPostServiceService', true],
        ], [
            'postService' => 'App\\Service\\PostService',
        ]))->withContext('App\\Controller\\PostController::create()', $container);
    }
}
