<?php

namespace ContainerU6o0Bxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHyLl__Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHyLl..' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHyLl..'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\UserController::show' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Admin\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\Admin\\UserController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController::update' => ['privates', '.service_locator.OA38qqg.App\\Controller\\Admin\\UserController::update()', 'getUserControllerupdateService', true],
            'App\\Controller\\Api\\LikeController::index' => ['privates', '.service_locator.pwqhacm.App\\Controller\\Api\\LikeController::index()', 'getLikeControllerindexService', true],
            'App\\Controller\\Api\\LikeController::get' => ['privates', '.service_locator._98tlIb.App\\Controller\\Api\\LikeController::get()', 'getLikeControllergetService', true],
            'App\\Controller\\Api\\LikeController::create' => ['privates', '.service_locator.RJ3ocas.App\\Controller\\Api\\LikeController::create()', 'getLikeControllercreateService', true],
            'App\\Controller\\Api\\LikeController::delete' => ['privates', '.service_locator.n7t1Uis.App\\Controller\\Api\\LikeController::delete()', 'getLikeControllerdeleteService', true],
            'App\\Controller\\Api\\LikeController::indexByPost' => ['privates', '.service_locator.7znPbMJ.App\\Controller\\Api\\LikeController::indexByPost()', 'getLikeControllerindexByPostService', true],
            'App\\Controller\\Api\\PostController::index' => ['privates', '.service_locator.jcYtTcg.App\\Controller\\Api\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\Api\\PostController::delete' => ['privates', '.service_locator.mlMhPL1.App\\Controller\\Api\\PostController::delete()', 'getPostControllerdeleteService', true],
            'App\\Controller\\Api\\PostController::patch' => ['privates', '.service_locator.mlMhPL1.App\\Controller\\Api\\PostController::patch()', 'getPostControllerpatchService', true],
            'App\\Controller\\Api\\PostController::feed' => ['privates', '.service_locator.BbCY9d..App\\Controller\\Api\\PostController::feed()', 'getPostControllerfeedService', true],
            'App\\Controller\\Api\\RespondController::get' => ['privates', '.service_locator.PGh0LTc.App\\Controller\\Api\\RespondController::get()', 'getRespondControllergetService', true],
            'App\\Controller\\Api\\RespondController::create' => ['privates', '.service_locator.egipcEH.App\\Controller\\Api\\RespondController::create()', 'getRespondControllercreateService', true],
            'App\\Controller\\Api\\RespondController::delete' => ['privates', '.service_locator.egipcEH.App\\Controller\\Api\\RespondController::delete()', 'getRespondControllerdeleteService', true],
            'App\\Controller\\Api\\SubscribeController::getFollowers' => ['privates', '.service_locator.67XUPCF.App\\Controller\\Api\\SubscribeController::getFollowers()', 'getSubscribeControllergetFollowersService', true],
            'App\\Controller\\Api\\SubscribeController::subscribe' => ['privates', '.service_locator.1vFMvPs.App\\Controller\\Api\\SubscribeController::subscribe()', 'getSubscribeControllersubscribeService', true],
            'App\\Controller\\Api\\SubscribeController::unsubscribe' => ['privates', '.service_locator.1vFMvPs.App\\Controller\\Api\\SubscribeController::unsubscribe()', 'getSubscribeControllerunsubscribeService', true],
            'App\\Controller\\Api\\UserController::profil' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Api\\UserController::profil()', 'getUserControllerprofilService', true],
            'App\\Controller\\Api\\UserController::updateRefresh' => ['privates', '.service_locator.OA38qqg.App\\Controller\\Api\\UserController::updateRefresh()', 'getUserControllerupdateRefreshService', true],
            'App\\Controller\\Login\\SecurityController::login' => ['privates', '.service_locator.g2TMuy3.App\\Controller\\Login\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\UserController:show' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Admin\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\Admin\\UserController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\Admin\\UserController:update' => ['privates', '.service_locator.OA38qqg.App\\Controller\\Admin\\UserController::update()', 'getUserControllerupdateService', true],
            'App\\Controller\\Api\\LikeController:index' => ['privates', '.service_locator.pwqhacm.App\\Controller\\Api\\LikeController::index()', 'getLikeControllerindexService', true],
            'App\\Controller\\Api\\LikeController:get' => ['privates', '.service_locator._98tlIb.App\\Controller\\Api\\LikeController::get()', 'getLikeControllergetService', true],
            'App\\Controller\\Api\\LikeController:create' => ['privates', '.service_locator.RJ3ocas.App\\Controller\\Api\\LikeController::create()', 'getLikeControllercreateService', true],
            'App\\Controller\\Api\\LikeController:delete' => ['privates', '.service_locator.n7t1Uis.App\\Controller\\Api\\LikeController::delete()', 'getLikeControllerdeleteService', true],
            'App\\Controller\\Api\\LikeController:indexByPost' => ['privates', '.service_locator.7znPbMJ.App\\Controller\\Api\\LikeController::indexByPost()', 'getLikeControllerindexByPostService', true],
            'App\\Controller\\Api\\PostController:index' => ['privates', '.service_locator.jcYtTcg.App\\Controller\\Api\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\Api\\PostController:delete' => ['privates', '.service_locator.mlMhPL1.App\\Controller\\Api\\PostController::delete()', 'getPostControllerdeleteService', true],
            'App\\Controller\\Api\\PostController:patch' => ['privates', '.service_locator.mlMhPL1.App\\Controller\\Api\\PostController::patch()', 'getPostControllerpatchService', true],
            'App\\Controller\\Api\\PostController:feed' => ['privates', '.service_locator.BbCY9d..App\\Controller\\Api\\PostController::feed()', 'getPostControllerfeedService', true],
            'App\\Controller\\Api\\RespondController:get' => ['privates', '.service_locator.PGh0LTc.App\\Controller\\Api\\RespondController::get()', 'getRespondControllergetService', true],
            'App\\Controller\\Api\\RespondController:create' => ['privates', '.service_locator.egipcEH.App\\Controller\\Api\\RespondController::create()', 'getRespondControllercreateService', true],
            'App\\Controller\\Api\\RespondController:delete' => ['privates', '.service_locator.egipcEH.App\\Controller\\Api\\RespondController::delete()', 'getRespondControllerdeleteService', true],
            'App\\Controller\\Api\\SubscribeController:getFollowers' => ['privates', '.service_locator.67XUPCF.App\\Controller\\Api\\SubscribeController::getFollowers()', 'getSubscribeControllergetFollowersService', true],
            'App\\Controller\\Api\\SubscribeController:subscribe' => ['privates', '.service_locator.1vFMvPs.App\\Controller\\Api\\SubscribeController::subscribe()', 'getSubscribeControllersubscribeService', true],
            'App\\Controller\\Api\\SubscribeController:unsubscribe' => ['privates', '.service_locator.1vFMvPs.App\\Controller\\Api\\SubscribeController::unsubscribe()', 'getSubscribeControllerunsubscribeService', true],
            'App\\Controller\\Api\\UserController:profil' => ['privates', '.service_locator.OzEre6h.App\\Controller\\Api\\UserController::profil()', 'getUserControllerprofilService', true],
            'App\\Controller\\Api\\UserController:updateRefresh' => ['privates', '.service_locator.OA38qqg.App\\Controller\\Api\\UserController::updateRefresh()', 'getUserControllerupdateRefreshService', true],
            'App\\Controller\\Login\\SecurityController:login' => ['privates', '.service_locator.g2TMuy3.App\\Controller\\Login\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\UserController::show' => '?',
            'App\\Controller\\Admin\\UserController::index' => '?',
            'App\\Controller\\Admin\\UserController::update' => '?',
            'App\\Controller\\Api\\LikeController::index' => '?',
            'App\\Controller\\Api\\LikeController::get' => '?',
            'App\\Controller\\Api\\LikeController::create' => '?',
            'App\\Controller\\Api\\LikeController::delete' => '?',
            'App\\Controller\\Api\\LikeController::indexByPost' => '?',
            'App\\Controller\\Api\\PostController::index' => '?',
            'App\\Controller\\Api\\PostController::delete' => '?',
            'App\\Controller\\Api\\PostController::patch' => '?',
            'App\\Controller\\Api\\PostController::feed' => '?',
            'App\\Controller\\Api\\RespondController::get' => '?',
            'App\\Controller\\Api\\RespondController::create' => '?',
            'App\\Controller\\Api\\RespondController::delete' => '?',
            'App\\Controller\\Api\\SubscribeController::getFollowers' => '?',
            'App\\Controller\\Api\\SubscribeController::subscribe' => '?',
            'App\\Controller\\Api\\SubscribeController::unsubscribe' => '?',
            'App\\Controller\\Api\\UserController::profil' => '?',
            'App\\Controller\\Api\\UserController::updateRefresh' => '?',
            'App\\Controller\\Login\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\UserController:show' => '?',
            'App\\Controller\\Admin\\UserController:index' => '?',
            'App\\Controller\\Admin\\UserController:update' => '?',
            'App\\Controller\\Api\\LikeController:index' => '?',
            'App\\Controller\\Api\\LikeController:get' => '?',
            'App\\Controller\\Api\\LikeController:create' => '?',
            'App\\Controller\\Api\\LikeController:delete' => '?',
            'App\\Controller\\Api\\LikeController:indexByPost' => '?',
            'App\\Controller\\Api\\PostController:index' => '?',
            'App\\Controller\\Api\\PostController:delete' => '?',
            'App\\Controller\\Api\\PostController:patch' => '?',
            'App\\Controller\\Api\\PostController:feed' => '?',
            'App\\Controller\\Api\\RespondController:get' => '?',
            'App\\Controller\\Api\\RespondController:create' => '?',
            'App\\Controller\\Api\\RespondController:delete' => '?',
            'App\\Controller\\Api\\SubscribeController:getFollowers' => '?',
            'App\\Controller\\Api\\SubscribeController:subscribe' => '?',
            'App\\Controller\\Api\\SubscribeController:unsubscribe' => '?',
            'App\\Controller\\Api\\UserController:profil' => '?',
            'App\\Controller\\Api\\UserController:updateRefresh' => '?',
            'App\\Controller\\Login\\SecurityController:login' => '?',
        ]);
    }
}
