<?php

namespace ContainerU6o0Bxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._98tlIb.App\Controller\Api\LikeController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._98tlIb.App\\Controller\\Api\\LikeController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'like' => ['privates', '.errored..service_locator._98tlIb.App\\Entity\\Like', NULL, 'Cannot autowire service ".service_locator._98tlIb": it needs an instance of "App\\Entity\\Like" but this type has been excluded in "config/services.yaml".'],
        ], [
            'like' => 'App\\Entity\\Like',
        ]))->withContext('App\\Controller\\Api\\LikeController::get()', $container);
    }
}
