<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKNzaxCV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKNzaxCV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKNzaxCV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKNzaxCV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKNzaxCV\App_KernelDevDebugContainer([
    'container.build_hash' => 'KNzaxCV',
    'container.build_id' => 'f008d33f',
    'container.build_time' => 1744207368,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKNzaxCV');
