<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF8fmB38\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF8fmB38/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF8fmB38.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF8fmB38\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF8fmB38\App_KernelDevDebugContainer([
    'container.build_hash' => 'F8fmB38',
    'container.build_id' => '81808839',
    'container.build_time' => 1744014299,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF8fmB38');
