<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'accessTokens' => [parent::class, 'accessTokens', null],
        "\0".parent::class."\0".'banniere' => [parent::class, 'banniere', null],
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null],
        "\0".parent::class."\0".'blockeds' => [parent::class, 'blockeds', null],
        "\0".parent::class."\0".'blockers' => [parent::class, 'blockers', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isBanned' => [parent::class, 'isBanned', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'locate' => [parent::class, 'locate', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'pdp' => [parent::class, 'pdp', null],
        "\0".parent::class."\0".'posts' => [parent::class, 'posts', null],
        "\0".parent::class."\0".'pseudo' => [parent::class, 'pseudo', null],
        "\0".parent::class."\0".'refresh' => [parent::class, 'refresh', null],
        "\0".parent::class."\0".'responds' => [parent::class, 'responds', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'url' => [parent::class, 'url', null],
        'accessTokens' => [parent::class, 'accessTokens', null],
        'banniere' => [parent::class, 'banniere', null],
        'bio' => [parent::class, 'bio', null],
        'blockeds' => [parent::class, 'blockeds', null],
        'blockers' => [parent::class, 'blockers', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'isBanned' => [parent::class, 'isBanned', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'locate' => [parent::class, 'locate', null],
        'password' => [parent::class, 'password', null],
        'pdp' => [parent::class, 'pdp', null],
        'posts' => [parent::class, 'posts', null],
        'pseudo' => [parent::class, 'pseudo', null],
        'refresh' => [parent::class, 'refresh', null],
        'responds' => [parent::class, 'responds', null],
        'roles' => [parent::class, 'roles', null],
        'url' => [parent::class, 'url', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
