<?php

namespace ContainerVpcxvPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n7t1Uis.App\Entity\Like' shared service.
     *
     * @return \App\Entity\Like
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.n7t1Uis": it needs an instance of "App\\Entity\\Like" but this type has been excluded in "config/services.yaml".');
    }
}
