<?php

namespace ContainerU1AXu9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lzr5D.b.App\Controller\Api\LikeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lzr5D.b.App\\Controller\\Api\\LikeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'likeRepo' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
        ], [
            'likeRepo' => 'App\\Repository\\LikeRepository',
        ]))->withContext('App\\Controller\\Api\\LikeController::index()', $container);
    }
}
