<?php

namespace ContainerU1AXu9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerprofilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OzEre6h.App\Controller\Api\UserController::profil()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OzEre6h.App\\Controller\\Api\\UserController::profil()'] = ($container->privates['.service_locator.OzEre6h'] ?? $container->load('get_ServiceLocator_OzEre6hService'))->withContext('App\\Controller\\Api\\UserController::profil()', $container);
    }
}
