<?php

namespace ContainerW4bBJZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jcYtTcg.App\Controller\Api\PostController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jcYtTcg.App\\Controller\\Api\\PostController::index()'] = ($container->privates['.service_locator.jcYtTcg'] ?? $container->load('get_ServiceLocator_JcYtTcgService'))->withContext('App\\Controller\\Api\\PostController::index()', $container);
    }
}
