<?php

namespace ContainerPdHOs41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1vFMvPsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vFMvPs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vFMvPs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.1vFMvPs.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.1vFMvPs": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'subscribeRepo' => ['privates', 'App\\Repository\\SubscribeRepository', 'getSubscribeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'subscribeRepo' => 'App\\Repository\\SubscribeRepository',
            'em' => '?',
        ]);
    }
}
