<?php

namespace ContainerPdHOs41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerfeedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BbCY9d..App\Controller\Api\PostController::feed()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BbCY9d..App\\Controller\\Api\\PostController::feed()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'subscribeRepository' => ['privates', 'App\\Repository\\SubscribeRepository', 'getSubscribeRepositoryService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'subscribeRepository' => 'App\\Repository\\SubscribeRepository',
        ]))->withContext('App\\Controller\\Api\\PostController::feed()', $container);
    }
}
