<?php

namespace Container1aG2lso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockedControllerpostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u8r71Yf.App\Controller\Api\BlockedController::post()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u8r71Yf.App\\Controller\\Api\\BlockedController::post()'] = ($container->privates['.service_locator.u8r71Yf'] ?? $container->load('get_ServiceLocator_U8r71YfService'))->withContext('App\\Controller\\Api\\BlockedController::post()', $container);
    }
}
