<?php

namespace Container1aG2lso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.95r6gX0.App\Controller\Api\PostController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.95r6gX0.App\\Controller\\Api\\PostController::delete()'] = ($container->privates['.service_locator.95r6gX0'] ?? $container->load('get_ServiceLocator_95r6gX0Service'))->withContext('App\\Controller\\Api\\PostController::delete()', $container);
    }
}
