<?php

namespace Container1aG2lso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepostControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\RepostController' shared autowired service.
     *
     * @return \App\Controller\Api\RepostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Security/BlockCheckerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/RepostController.php';

        $container->services['App\\Controller\\Api\\RepostController'] = $instance = new \App\Controller\Api\RepostController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\RepostController', $container));

        return $instance;
    }
}
