<?php

namespace Container1aG2lso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepostControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TlmNs2r.App\Controller\Api\RepostController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TlmNs2r.App\\Controller\\Api\\RepostController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repostRepository' => ['privates', 'App\\Repository\\RepostRepository', 'getRepostRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repostRepository' => 'App\\Repository\\RepostRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Api\\RepostController::get()', $container);
    }
}
