<?php

namespace ContainerAFXU1wf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllerindexByPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7znPbMJ.App\Controller\Api\LikeController::indexByPost()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7znPbMJ.App\\Controller\\Api\\LikeController::indexByPost()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'likeRepo' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'likeRepo' => 'App\\Repository\\LikeRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Api\\LikeController::indexByPost()', $container);
    }
}
