<?php

namespace ContainerHaQxg7Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockedControllergetBlockedsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EOzm1G1.App\Controller\Api\BlockedController::getBlockeds()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EOzm1G1.App\\Controller\\Api\\BlockedController::getBlockeds()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.EOzm1G1.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EOzm1G1": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'blockedRepo' => ['privates', 'App\\Repository\\BlockedRepository', 'getBlockedRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'blockedRepo' => 'App\\Repository\\BlockedRepository',
        ]))->withContext('App\\Controller\\Api\\BlockedController::getBlockeds()', $container);
    }
}
