<?php

namespace ContainerHaQxg7Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n7t1Uis.App\Controller\Api\LikeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n7t1Uis.App\\Controller\\Api\\LikeController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'like' => ['privates', '.errored..service_locator.n7t1Uis.App\\Entity\\Like', NULL, 'Cannot autowire service ".service_locator.n7t1Uis": it needs an instance of "App\\Entity\\Like" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'like' => 'App\\Entity\\Like',
            'em' => '?',
        ]))->withContext('App\\Controller\\Api\\LikeController::delete()', $container);
    }
}
