<?php

namespace ContainerHaQxg7Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRespondControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGh0LTc.App\Controller\Api\RespondController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PGh0LTc.App\\Controller\\Api\\RespondController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'respondRepository' => ['privates', 'App\\Repository\\RespondRepository', 'getRespondRepositoryService', true],
        ], [
            'respondRepository' => 'App\\Repository\\RespondRepository',
        ]))->withContext('App\\Controller\\Api\\RespondController::get()', $container);
    }
}
