<?php

namespace ContainerQOGJtf5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllersearchPostsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hLvJhZ4.App\Controller\Api\PostController::searchPosts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hLvJhZ4.App\\Controller\\Api\\PostController::searchPosts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'repostRepository' => ['privates', 'App\\Repository\\RepostRepository', 'getRepostRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'repostRepository' => 'App\\Repository\\RepostRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\Api\\PostController::searchPosts()', $container);
    }
}
