<?php

namespace ContainerQOGJtf5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepostControllercheckIfBlockedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ZSKOQS.App\Controller\Api\RepostController::checkIfBlocked()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ZSKOQS.App\\Controller\\Api\\RepostController::checkIfBlocked()'] = ($container->privates['.service_locator.8ZSKOQS'] ?? $container->load('get_ServiceLocator_8ZSKOQSService'))->withContext('App\\Controller\\Api\\RepostController::checkIfBlocked()', $container);
    }
}
